on:
  pull_request:
    branches: master
    paths: 'code/drasil-*'
name: Linter
defaults:
  run:
    shell: bash
    working-directory: code
jobs:
  linter:
    name: "HLint"
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: "HLint"
        run: make hot_hlint
